binary_sensor:
  - platform: template
    id: id_bin_bl_state
    name: "Device active"
    on_press:
      then:
        - light.turn_on: 
            id: id_light_backlight_brightness
            brightness: !lambda return id(id_num_awake_backlight_brightness).state / 100.0;
            transition_length: 300ms
            color_mode: BRIGHTNESS
    on_release:
      then:
        - light.turn_on:
            id: id_light_backlight_brightness
            brightness: !lambda return id(id_num_idle_backlight_brightness).state / 100.0;
            transition_length: 1500ms
            color_mode: BRIGHTNESS
        - lvgl.page.show:
            id: page_home
            animation: FADE_OUT
            time: 300ms
        - delay: 100ms
#        - lvgl.pause: